#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --partition=compute_full_node
#SBATCH --time=00:16:00  # H:M:S
#SBATCH --mail-type=ALL
#SBATCH --account=soscip-3-045

cd $SLURM_SUBMIT_DIR # go to code/script directory

# loads modules 
module --force purge  # delete all module
module load anaconda3
module load cuda/10.2.89

source activate mist_env2 #name of your environment

python main.py pics 0,1,2,3 > output.txt

hostname
nvidia-smi #use this to get the cuda report
